version: "1.0"
stages:
  - "clone"
  - "install"
  - "build"
  - "push"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "codefresh-io/cf-debugger"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  install:
    title: "Install Docker Image"
    image: node:16.20.1
    stage: "install"
    shell: bash
    commands:
      - yarn install --frozen-lockfile --production && yarn cache clean
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "codefresh/cf-debugger"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  add_git_tag:
    title: "Add Git tag"
    stage: "build"
    image: codefreshio/ci-helpers
    shell: bash
    commands:
      - 'export PACKAGE_VERSION=$(jq -r ".version" package.json)'
      - "echo Current version: $PACKAGE_VERSION"
      - "cf_export PACKAGE_VERSION"
      - |-
        source /get-token/get-gh-token.sh
        if [[ "$(git describe --tags --abbrev=0)" == "${PACKAGE_VERSION}" ]]; then
          echo "Git tag is already created, skipping..."
          exit 0
        fi
        curl --fail -X POST -d "{\"ref\": \"refs/tags/${PACKAGE_VERSION}\", \"sha\": \"${CF_REVISION}\"}" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${CF_REPO_OWNER}/${CF_REPO_NAME}/git/refs
    when:
      branch:
        only: [ master ]

  parallel_push:
    type: "parallel"
    stage: "push"
    steps:
      push_to_registry_branch:
        title: "Pushing image to registry with branch name"
        type: push
        registry: ${{REGISTRY_INTEGRATION_QUAY}}
        candidate: ${{build}}
        tags:
        - ${{CF_BRANCH_TAG_NORMALIZED}}

      push_to_registry_quay:
        title: "Pushing image to quay registry"
        type: "push"
        registry: ${{REGISTRY_INTEGRATION_QUAY}}
        candidate: ${{build}}
        image_name: "codefresh/${{CF_REPO_NAME}}"
        tags:
        - ${{PACKAGE_VERSION}}
        - latest
        when:
          branch:
            only: [ master ]

      push_to_registry_dockerhub:
        title: "Pushing image to dockerhub registry"
        type: "push"
        registry: "dockerhub"
        candidate: ${{build}}
        image_name: "codefresh/${{CF_REPO_NAME}}"
        tags:
        - ${{PACKAGE_VERSION}}
        - latest
        when:
          branch:
            only: [ master ]
